"use client";

import React, { useEffect, useState } from "react";
import { supabase } from "@/app/lib/supabase";
import { Partner, PartnerType } from "@/app/lib/admin/types";
import { Search, Plus, Edit, MoreVertical, X, Save } from "lucide-react";

export default function PartnersPage() {
    const [partners, setPartners] = useState<Partner[]>([]);
    const [loading, setLoading] = useState(true);
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [editingId, setEditingId] = useState<string | null>(null);

    // Form State
    const [formData, setFormData] = useState<Partial<Partner>>({
        type: 'both',
        status: 'active'
    });

    const fetchPartners = async () => {
        setLoading(true);
        const { data, error } = await supabase
            .from("partners")
            .select("*")
            .order("created_at", { ascending: false });

        if (error) {
            console.error("Error fetching partners:", error);
            // Fallback for demo if table missing? No, let's assume user runs SQL.
        } else {
            setPartners(data || []);
        }
        setLoading(false);
    };

    useEffect(() => {
        fetchPartners();
    }, []);

    const handleOpenModal = (partner?: Partner) => {
        if (partner) {
            setEditingId(partner.id);
            setFormData(partner);
        } else {
            setEditingId(null);
            setFormData({ type: 'both', status: 'active', name: '', business_number: '', contact_name: '', contact_phone: '', address: '' });
        }
        setIsModalOpen(true);
    };

    const handleSave = async () => {
        if (!formData.name) return alert("거래처명은 필수입니다.");

        const payload = {
            ...formData,
            // If new, id is auto-generated by DB
        };

        let error;
        if (editingId) {
            const { error: e } = await supabase.from("partners").update(payload).eq("id", editingId);
            error = e;
        } else {
            const { error: e } = await supabase.from("partners").insert([payload]);
            error = e;
        }

        if (error) {
            alert("저장 실패: " + error.message);
        } else {
            setIsModalOpen(false);
            fetchPartners();
        }
    };

    return (
        <div className="space-y-6 h-full flex flex-col">
            <div className="flex justify-between items-center">
                <div>
                    <h1 className="text-2xl font-bold text-slate-800">거래처 관리</h1>
                    <p className="text-sm text-slate-500">매입/매출처 등록 및 정보 수정</p>
                </div>
                <button
                    onClick={() => handleOpenModal()}
                    className="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition"
                >
                    <Plus size={18} />
                    신규 거래처
                </button>
            </div>

            {/* Content */}
            <div className="flex-1 bg-white rounded-xl border shadow-sm flex flex-col overflow-hidden">
                {/* Search Bar? (Skipped for brevity) */}
                <div className="overflow-x-auto flex-1">
                    <table className="w-full text-sm text-left text-slate-600">
                        <thead className="bg-slate-50 text-xs uppercase font-bold text-slate-500 border-b">
                            <tr>
                                <th className="px-6 py-3">업체명/유형</th>
                                <th className="px-6 py-3">사업자번호</th>
                                <th className="px-6 py-3">담당자</th>
                                <th className="px-6 py-3">연락처</th>
                                <th className="px-6 py-3 text-right">관리</th>
                            </tr>
                        </thead>
                        <tbody>
                            {loading ? (
                                <tr><td colSpan={5} className="p-8 text-center">Loading...</td></tr>
                            ) : partners.length === 0 ? (
                                <tr><td colSpan={5} className="p-8 text-center text-slate-400">데이터가 없습니다.</td></tr>
                            ) : (
                                partners.map(p => (
                                    <tr key={p.id} className="border-b hover:bg-slate-50">
                                        <td className="px-6 py-4">
                                            <div className="font-bold text-slate-900">{p.name}</div>
                                            <span className={`text-[10px] px-2 py-0.5 rounded-full border ${p.type === 'supplier' ? 'bg-blue-50 text-blue-600 border-blue-200' :
                                                    p.type === 'customer' ? 'bg-green-50 text-green-600 border-green-200' :
                                                        'bg-purple-50 text-purple-600 border-purple-200'
                                                }`}>
                                                {p.type === 'supplier' ? '매입처' : p.type === 'customer' ? '매출처' : '매입/매출'}
                                            </span>
                                        </td>
                                        <td className="px-6 py-4 font-mono">{p.business_number || '-'}</td>
                                        <td className="px-6 py-4">{p.contact_name || '-'}</td>
                                        <td className="px-6 py-4">{p.contact_phone || '-'}</td>
                                        <td className="px-6 py-4 text-right">
                                            <button onClick={() => handleOpenModal(p)} className="p-2 hover:bg-slate-200 rounded-full">
                                                <Edit size={16} />
                                            </button>
                                        </td>
                                    </tr>
                                ))
                            )}
                        </tbody>
                    </table>
                </div>
            </div>

            {/* Modal */}
            {isModalOpen && (
                <div className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4">
                    <div className="bg-white w-full max-w-md rounded-2xl shadow-2xl overflow-hidden animate-in fade-in zoom-in duration-200">
                        <div className="px-6 py-4 border-b flex justify-between items-center bg-slate-50">
                            <h3 className="font-bold text-lg">{editingId ? '거래처 수정' : '신규 거래처 등록'}</h3>
                            <button onClick={() => setIsModalOpen(false)}><X size={20} /></button>
                        </div>
                        <div className="p-6 space-y-4">
                            <div>
                                <label className="block text-xs font-bold text-slate-500 mb-1">거래처 유형</label>
                                <div className="flex gap-2">
                                    {['supplier', 'customer', 'both'].map(t => (
                                        <button
                                            key={t}
                                            onClick={() => setFormData({ ...formData, type: t as any })}
                                            className={`flex-1 py-2 text-sm rounded-lg border font-bold transition ${formData.type === t ? 'bg-indigo-600 text-white border-indigo-600' : 'bg-white text-slate-600 border-slate-200 hover:bg-slate-50'
                                                }`}
                                        >
                                            {t === 'supplier' ? '매입' : t === 'customer' ? '매출' : '공통'}
                                        </button>
                                    ))}
                                </div>
                            </div>
                            <div>
                                <label className="block text-xs font-bold text-slate-500 mb-1">거래처명 <span className="text-red-500">*</span></label>
                                <input className="w-full p-2 border rounded-lg" value={formData.name || ''} onChange={e => setFormData({ ...formData, name: e.target.value })} placeholder="(주)한국유리" />
                            </div>
                            <div className="grid grid-cols-2 gap-3">
                                <div>
                                    <label className="block text-xs font-bold text-slate-500 mb-1">사업자번호</label>
                                    <input className="w-full p-2 border rounded-lg" value={formData.business_number || ''} onChange={e => setFormData({ ...formData, business_number: e.target.value })} placeholder="000-00-00000" />
                                </div>
                                <div>
                                    <label className="block text-xs font-bold text-slate-500 mb-1">담당자</label>
                                    <input className="w-full p-2 border rounded-lg" value={formData.contact_name || ''} onChange={e => setFormData({ ...formData, contact_name: e.target.value })} placeholder="김철수" />
                                </div>
                            </div>
                            <div>
                                <label className="block text-xs font-bold text-slate-500 mb-1">연락처</label>
                                <input className="w-full p-2 border rounded-lg" value={formData.contact_phone || ''} onChange={e => setFormData({ ...formData, contact_phone: e.target.value })} placeholder="010-1234-5678" />
                            </div>
                        </div>
                        <div className="p-4 border-t bg-slate-50 flex justify-end gap-2">
                            <button onClick={() => setIsModalOpen(false)} className="px-4 py-2 text-slate-600 font-bold hover:bg-slate-200 rounded-lg">취소</button>
                            <button onClick={handleSave} className="px-4 py-2 bg-indigo-600 text-white font-bold rounded-lg hover:bg-indigo-700 flex items-center gap-2">
                                <Save size={16} /> 저장
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}
